export const paintColors: Record<number, string> = {
  1: 'Red',
  2: 'Orange',
  3: 'Yellow',
  4: 'Lime',
  5: 'Green',
  6: 'Teal',
  7: 'Cyan',
  8: 'Sky Blue',
  9: 'Blue',
  10: 'Purple',
  11: 'Violet',
  12: 'Pink',
  13: 'Deep Red',
  14: 'Deep Orange',
  15: 'Deep Yellow',
  16: 'Deep Lime',
  17: 'Deep Green',
  18: 'Deep Teal',
  19: 'Deep Cyan',
  20: 'Deep Sky Blue',
  21: 'Deep Blue',
  22: 'Deep Purple',
  23: 'Deep Violet',
  24: 'Deep Pink',
  25: 'Black',
  26: 'White',
  27: 'Gray',
  28: 'Brown',
  29: 'Shadow',
  30: 'Negative',
  31: 'Illuminant',
};
